const lyricsData = {
    "supernova.mp3": [
        { time: 3, text: "I'm like some kind of supernova" },
        { time: 7, text: "Watch out" },
        { time: 8, text: "Look at me go, 재미 좀 볼" },
        { time: 11.5, text: "빛의 core, so hot, hot" },
        { time: 16, text: "문이 열려 서로의 존재를 느껴" },
        { time: 19, text: "마치 Discord, 날 닮은 너 (incoming!), 너 누구야? (Drop)" },
        { time: 24, text: "사건은 다가와, ah-oh, ayy" },
        { time: 26.5, text: "거세게 커져가, ah-oh, ayy" },
        { time: 28.5, text: "That tick, that tick, tick bomb" },
        { time: 30, text: "That tick, that tick, tick bomb" },
        { time: 32.8, text: "감히 건드리지 못할 걸 (누구도 말이야)" },
        { time: 37.5, text: "지금 내 안에선 (su-su-su-supernova)" },
        { time: 40, text: "Nova, can't stop hyperstellar" },
        { time: 46, text: "원초 그걸 찾아" },
        { time: 49, text: "Bring the light of a dying star" },
        { time: 50.8, text: "불러낸 내 우주를 봐봐, supernova" },
        { time: 58, text: "Ah, body bang (bang, bang, bang)" },
        { time: 63, text: "Make it feel too right" },
        { time: 65, text: "휩쓸린 energy, it's so special" },
        { time: 68.5, text: "잔인한 queen 이며 scene 이자 종결" },
        { time: 72.5, text: "이토록 거대한 내 안의 explosion" },
        { time: 76.6, text: "내 모든 세포 별로부터 만들어져 (under my control)" },
        { time: 80.7, text: "질문은 계속돼, ah-oh, ayy" },
        { time: 82.8, text: "우린 어디서 왔나, oh, ayy" },
        { time: 85, text: "느껴 내 안에선, huh (su-su-su-supernova)" },
        { time: 88.5, text: "Nova, can't stop hyperstellar" },
        { time: 94, text: "원초 그걸 찾아" },
        { time: 97.3, text: "Bring the light of a dying star" },
        { time: 98.8, text: "불러낸 내 우주를 봐봐, supernova" },
        { time: 104.5, text: "보이지 않는 힘으로 네게 손 내밀어 볼까?" },
        { time: 112.5, text: "가능한 모든 가능성, 무한 속의 너를 만나" },
        { time: 116.6, text: "It's about to bang, bang, don't forget my name" },
        { time: 120.3, text: "Su-su-su-supernova" },
        { time: 122.2, text: "사건은 다가와, ah-oh, ayy" },
        { time: 124.5, text: "거세게 커져가, ah-oh, ayy" },
        { time: 127, text: "질문은 계속돼, ah-oh, ayy" },
        { time: 129, text: "우린 어디서 왔나, oh, ayy" },
        { time: 130.8, text: "사건은 다가와, ah-oh, ayy" },
        { time: 133, text: "거세게 커져가, ah-oh, ayy" },
        { time: 134.5, text: "Tell me, tell me, tell me, oh, ayy" },
        { time: 137, text: "우린 어디서 왔나, oh, ayy, 우린 어디서 왔나, oh, ayy" },
        { time: 142.5, text: "Nova (nova), can't stop hyperstellar" },
        { time: 146.8, text: "(Hyperstellar) 원초 그걸 찾아" },
        { time: 151, text: "Bring the light of a dying star (light of a dying star)" },
        { time: 152.5, text: "불러낸 내 우주를 봐봐 (all the way), supernova (hey, huh)" },
        { time: 159, text: "사건은 다가와, ah-oh, ayy (new star)" },
        { time: 161, text: "거세게 커져가, ah-oh, ayy" },
        { time: 162.5, text: "질문은 계속돼 (nova), ah-oh, ayy (ah-ah)" },
        { time: 165, text: "우린 어디서 왔나, oh, ayy" },
        { time: 166.5, text: "사건은 다가와, ah-oh, ayy (yeah, yeah, yeah, yеah)" },
        { time: 169, text: "거세게 커져가, ah-oh, ayy (nova)" },
        { time: 171, text: "질문은 계속돼, ah-oh, ayy (bring the light of a dying star)" },
        { time: 173, text: "Supernova" }
    ],
    "kill-it.mp3": [
        { time: 2, text: "Kill it (Slish, slash)" },
        { time: 9999, text: "Kill it, ooh (I-I)" },
        { time: 9999, text: "I drop the beat, I-I make you weak" },
        { time: 9999, text: "I-I hit delete, 경고 없이 비춘 빛" },
        { time: 9999, text: "Da-da, 다가오지 빠르게 날아들지" },
        { time: 9999, text: "한 번에 날 끌어당겨" },
        { time: 9999, text: "But I know I gotta risk it all, I won't ask you" },
        { time: 9999, text: "What I wanna do is all I do" },
        { time: 9999, text: "I don't rescue, 시선들을 즐겨주겠어" },
        { time: 9999, text: "Flash, flash, 관심 먹은 killa (Slash)" },
        { time: 9999, text: "가까이 더 유인한 다음 (Let you fall)" },
        { time: 9999, text: "No, 그림자처럼 번진 panic" },
        { time: 9999, text: "Break the wall, 날 가둔 모든 경계를 ruin" },
        { time: 9999, text: "더 넓은 세상을 보여줄게" },
        { time: 9999, text: "커져갈 my area (Kill it)" },
        { time: 9999, text: "I-I-I-I-I-I kill it" },
        { time: 9999, text: "Kill it on the spot, kill it, kill it on the shot like" },
        { time: 9999, text: "I-I-I-I-I-I kill it" },
        { time: 9999, text: "틀림없이 난, kill it, kill it on the dot like" },
        { time: 9999, text: "날 방해할수록" },
        { time: 9999, text: "유리해질 테니, I'm better" },
        { time: 9999, text: "I'ma shine as I watch the bodies drop" },
        { time: 9999, text: "I'm so good at it, uh" },
        { time: 9999, text: "너를 뒤흔들어" },
        { time: 9999, text: "I keep moving really quick" },
        { time: 9999, text: "And I feel that you are dramatic (What?)" },
        { time: 9999, text: "나는 anomaly (Yeah), 넘치는 jealousy (What?)" },
        { time: 9999, text: "위험한 fantasy (Yeah), okay, wait" },
        { time: 9999, text: "Kill it 헛소리, kill it 잔소리 (Wait)" },
        { time: 9999, text: "가쁜 숨소리 옅은 목소리 (Wait)" },
        { time: 9999, text: "Call the doctor (Bring)" },
        { time: 9999, text: "I'ma go, let you go make you fall (Let you fall)" },
        { time: 9999, text: "No, 망설임 따윈 없어 do it" },
        { time: 9999, text: "On the road, 날 가둔 모든 편견을 ruin" },
        { time: 9999, text: "모르던 세상을 깨닫게 해" },
        { time: 9999, text: "커져간 my area (Kill it)" },
        { time: 9999, text: "I-I-I-I-I-I kill it" },
        { time: 9999, text: "Kill it on the spot, kill it, kill it on the shot like" },
        { time: 9999, text: "I-I-I-I-I-I kill it" },
        { time: 9999, text: "틀림없이 난, kill it, kill it on the dot like" },
        { time: 9999, text: "날 방해할수록" },
        { time: 9999, text: "유리해질 테니, I'm better" },
        { time: 9999, text: "I'ma shine as I watch the bodies drop, kill it" },
        { time: 9999, text: "Keep off my side, keep out of my sight" },
        { time: 9999, text: "날 향한 잣대 위에서 춤을 출 거야 난" },
        { time: 9999, text: "Keep off my side, keep out of my sight" },
        { time: 9999, text: "널 무너뜨릴 거야 'cause I kill it, everybody right" },
        { time: 9999, text: "싹 다 날려버려 싹 다 날려" },
        { time: 9999, text: "전부 싹 다 날려버려 싹 다 ow!" },
        { time: 9999, text: "싹 다 지워버려 싹 다 지워" },
        { time: 9999, text: "전부 싹 다 지워버려 싹 다 you know I'ma" },
        { time: 9999, text: "I-I-I-I-I-I kill it" },
        { time: 9999, text: "Kill it on the spot, kill it, kill it on the shot like" },
        { time: 9999, text: "I-I-I-I-I-I kill it" },
        { time: 9999, text: "틀림없이 난, kill it, kill it on the dot like" },
        { time: 9999, text: "날 방해할수록 더 강해질 테니, I'm better" },
        { time: 9999, text: "I'ma shine as I watch the bodies drop, kill it" },

    ]

};
